### ISSUE TITLE
cant selfhost

### ISSUE THREAD

**Issue by pdaly14** [BlacketPS/Blacket#111]
node.js just cant find package.json

**Comment by ItsSyfe** [comment]
https://github.com/BlacketPS/Blacket#selfhost

**Comment by pdaly14** [comment]
> Run the backend and frontend individually. It is recommended to run using [Bun](https://bun.sh/). It is also advised to use [Bun as a PM2 interpreter](https://bun.sh/guides/ecosystem/pm2) to launch Blacket on startup and restart it if it crashes.

ok, i will try that, but i have little to no skills whatsoever, and i am doing the most basic things,, so i will probably still fail
