### ISSUE TITLE
I wana clap you OneDumbDuck

### ISSUE THREAD

**Issue by Natromacrolover** [BlacketPS/Blacket#119]
One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap One dumb duck plase let me clap you I just wana clap you

**Comment by regedit-sys** [comment]
NAK
